services:
  oetexam-frontend:
    image: ghcr.io/belalju/oetexam-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oetexam-frontend
    ports:
      - "80:80"
    networks:
      - oetexam-net
    restart: unless-stopped

networks:
  oetexam-net:
    external: true
